import { T } from './shared/blockFactory';
import { getStorefrontTemplate } from './registry';

export function visualTreatmentForTemplate(templateId, type, index) {
  const isHero = type === T.HERO;
  const isListing = [T.PROPERTIES, T.FEATURED_LISTINGS, T.TOP_LISTINGS, T.SOLD_LISTINGS].includes(type);
  const isTool = [T.MORTGAGE_CALCULATOR, T.CLOSING_COST_ESTIMATOR].includes(type);
  const palette = {
    'agent-classic': {
      bg: index % 2 === 0 ? '#ffffff' : '#f8fafc',
      align: isHero ? 'left' : 'left',
      padding: isHero ? 'large' : 'medium',
      radius: 'default',
      variant: isHero ? 'standard' : isListing ? 'feature-grid' : 'standard',
      cardStyle: 'bordered',
      columns: isListing ? '4' : '3',
      mediaPosition: isHero ? 'background' : 'none',
      width: 'full',
      shadow: 'small',
    },
    'agent-luxury-advisor': {
      bg: index % 2 === 0 ? '#faf7ef' : '#ffffff',
      align: isHero ? 'left' : 'center',
      padding: isHero ? 'large' : 'large',
      radius: index % 2 === 0 ? 'large' : 'default',
      variant: isHero ? 'premium' : isListing ? 'editorial' : 'split',
      cardStyle: 'elevated',
      columns: isListing ? '4' : '2',
      mediaPosition: isHero ? 'background' : 'right',
      width: 'full',
      shadow: 'large',
    },
    'agent-first-home': {
      bg: index % 2 === 0 ? '#eff6ff' : '#fff7ed',
      align: isHero || index < 3 ? 'center' : 'left',
      padding: 'medium',
      radius: 'large',
      variant: isHero ? 'feature-grid' : isTool ? 'lead-magnet' : 'standard',
      cardStyle: 'glass',
      columns: '2',
      mediaPosition: isHero ? 'background' : 'none',
      width: 'contained',
      shadow: 'medium',
    },
    'agent-investor': {
      bg: index % 2 === 0 ? '#ffffff' : '#f8fafc',
      align: 'left',
      padding: index <= 2 ? 'large' : 'medium',
      radius: 'none',
      variant: isListing ? 'feature-grid' : 'minimal',
      cardStyle: 'bordered',
      columns: isListing ? '4' : '2',
      mediaPosition: isHero ? 'background' : 'none',
      width: isListing ? 'full' : 'full',
      shadow: 'none',
    },
    'agent-seller-expert': {
      bg: index % 2 === 0 ? '#fff1f2' : '#fffbeb',
      align: isHero ? 'center' : 'left',
      padding: 'medium',
      radius: 'large',
      variant: isTool ? 'lead-magnet' : isHero ? 'split' : 'standard',
      cardStyle: 'elevated',
      columns: '2',
      mediaPosition: isHero ? 'right' : 'none',
      width: isTool ? 'narrow' : 'contained',
      shadow: 'medium',
    },
    'agent-community-expert': {
      bg: index % 2 === 0 ? '#f0fdf4' : '#fff7ed',
      align: index <= 1 ? 'center' : 'left',
      padding: 'medium',
      radius: 'large',
      variant: isHero ? 'editorial' : 'feature-grid',
      cardStyle: 'glass',
      columns: '3',
      mediaPosition: isHero ? 'background' : 'none',
      width: 'contained',
      shadow: 'medium',
    },
    'mortgage_broker-classic': {
      bg: index % 2 === 0 ? '#f8fafc' : '#ffffff',
      align: isHero ? 'left' : 'center',
      padding: isTool ? 'large' : 'medium',
      radius: isTool ? 'large' : 'default',
      variant: isHero ? 'split' : isTool ? 'lead-magnet' : 'feature-grid',
      cardStyle: isTool ? 'elevated' : 'bordered',
      columns: '3',
      mediaPosition: isHero ? 'right' : 'none',
      width: isTool ? 'narrow' : 'contained',
      shadow: isTool ? 'large' : 'small',
    },
    'mortgage_broker-first-home': {
      bg: index % 2 === 0 ? '#eff6ff' : '#fff7ed',
      align: isHero || isTool ? 'center' : 'left',
      padding: isHero || isTool ? 'large' : 'medium',
      radius: 'large',
      variant: isHero ? 'editorial' : isTool ? 'lead-magnet' : 'standard',
      cardStyle: 'glass',
      columns: '2',
      mediaPosition: isHero ? 'background' : 'none',
      width: isTool ? 'narrow' : 'contained',
      shadow: 'medium',
    },
    'mortgage_broker-wealth': {
      bg: index % 2 === 0 ? '#f5f3ff' : '#fff7ed',
      align: isHero ? 'center' : 'left',
      padding: 'large',
      radius: 'default',
      variant: 'premium',
      cardStyle: 'elevated',
      columns: '2',
      mediaPosition: isHero ? 'background' : 'right',
      width: 'contained',
      shadow: 'large',
    },
    'mortgage_broker-renewal': {
      bg: index % 2 === 0 ? '#ecfeff' : '#ffffff',
      align: isHero ? 'center' : 'left',
      padding: isHero || isTool ? 'large' : 'medium',
      radius: 'large',
      variant: isHero ? 'lead-magnet' : isTool ? 'split' : 'standard',
      cardStyle: 'elevated',
      columns: '2',
      mediaPosition: isHero ? 'background' : 'none',
      width: isHero || isTool ? 'narrow' : 'contained',
      shadow: 'medium',
    },
    'mortgage_broker-commercial': {
      bg: index % 2 === 0 ? '#f8fafc' : '#fef3c7',
      align: 'left',
      padding: 'large',
      radius: 'none',
      variant: 'minimal',
      cardStyle: 'bordered',
      columns: '3',
      mediaPosition: 'none',
      width: 'full',
      shadow: 'none',
    },
    'lawyer-classic': {
      bg: index % 2 === 0 ? '#f8fafc' : '#ffffff',
      align: isHero ? 'left' : 'center',
      padding: isHero || isTool ? 'large' : 'medium',
      radius: 'default',
      variant: isHero ? 'split' : isTool ? 'lead-magnet' : 'editorial',
      cardStyle: isTool ? 'elevated' : 'bordered',
      columns: '2',
      mediaPosition: isHero ? 'right' : 'none',
      width: isTool ? 'narrow' : 'contained',
      shadow: isTool ? 'large' : 'small',
    },
    'lawyer-first-home-closing': {
      bg: index % 2 === 0 ? '#eff6ff' : '#ffffff',
      align: isHero || isTool ? 'center' : 'left',
      padding: isHero || isTool ? 'large' : 'medium',
      radius: 'large',
      variant: isHero ? 'editorial' : isTool ? 'lead-magnet' : 'standard',
      cardStyle: 'glass',
      columns: '2',
      mediaPosition: isHero ? 'background' : 'none',
      width: isTool ? 'narrow' : 'contained',
      shadow: 'medium',
    },
    'lawyer-commercial': {
      bg: index % 2 === 0 ? '#f8fafc' : '#fef3c7',
      align: 'left',
      padding: 'large',
      radius: 'none',
      variant: 'minimal',
      cardStyle: 'bordered',
      columns: '2',
      mediaPosition: 'none',
      width: 'full',
      shadow: 'none',
    },
    'lawyer-investor': {
      bg: index % 2 === 0 ? '#f5f3ff' : '#ffffff',
      align: 'left',
      padding: isHero ? 'large' : 'medium',
      radius: 'none',
      variant: isTool ? 'lead-magnet' : 'minimal',
      cardStyle: 'bordered',
      columns: '2',
      mediaPosition: 'none',
      width: isTool ? 'narrow' : 'full',
      shadow: 'none',
    },
    'lawyer-newcomer': {
      bg: index % 2 === 0 ? '#f0fdf4' : '#fff7ed',
      align: isHero || isTool ? 'center' : 'left',
      padding: 'medium',
      radius: 'large',
      variant: isHero ? 'feature-grid' : isTool ? 'lead-magnet' : 'standard',
      cardStyle: 'glass',
      columns: '2',
      mediaPosition: isHero ? 'background' : 'none',
      width: 'contained',
      shadow: 'medium',
    },
  }[templateId];

  if (palette) return palette;

  return {
    bg: index % 2 === 0 ? '#ffffff' : '#f8fafc',
    align: isHero ? 'left' : 'left',
    padding: isHero ? 'large' : 'medium',
    radius: 'default',
    variant: isHero ? 'standard' : isTool ? 'lead-magnet' : 'standard',
    cardStyle: 'bordered',
    columns: '3',
    mediaPosition: isHero ? 'background' : 'none',
    width: isTool ? 'narrow' : 'full',
    shadow: 'small',
  };
}

/** Theme-aware default surfaces for property listing cards. */
export function listingCardThemeFromTemplate(templateKey = '') {
  const template = getStorefrontTemplate(templateKey);
  const brand = template?.brand || {};
  const byTemplate = {
    'agent-luxury-advisor': { card_background: '#fffdf8', card_text_color: '', cardStyle: 'elevated' },
    'agent-first-home': { card_background: '#ffffff', card_text_color: '', cardStyle: 'glass' },
    'agent-investor': { card_background: '#ffffff', card_text_color: '', cardStyle: 'bordered' },
    'agent-seller-expert': { card_background: '#ffffff', card_text_color: '', cardStyle: 'elevated' },
    'agent-community-expert': { card_background: '#ffffff', card_text_color: '', cardStyle: 'glass' },
    'agent-classic': { card_background: '#ffffff', card_text_color: '', cardStyle: 'bordered' },
  };
  const preset = byTemplate[templateKey] || {
    card_background: '#ffffff',
    card_text_color: '',
    cardStyle: 'bordered',
  };
  return {
    ...preset,
    card_background: preset.card_background || brand.page_background || '#ffffff',
  };
}
