import { block, brand, T } from '../shared/blockFactory';

const lawyerClassic = {
  id: 'lawyer-classic',
  role: 'lawyer',
  experience: 'classic-balanced',
  label: 'Real Estate Lawyer Classic',
  tagline: 'Classic gold-and-charcoal legal practice',
  description: 'A 15-layer gold-and-charcoal legal practice: counsel snapshot, documents, fees, intake, and closing guidance.',
  features: ['Who we help', 'Expertise snapshot', 'Practice areas', 'Document checklist', 'Fee guidance', 'Closing guide'],
  brand: brand('#202020', '#d39a52', 'Inter', 'square', 'editorial', '#ffffff'),
  blocks: (ctx) => [
    block(T.HERO, {
      heading: ctx.headline || 'Tell us about your matter.',
      body: ctx.tagline || 'Clear legal guidance for contracts, title matters, purchases, sales, and closing day.',
      primary_cta_label: 'Submit inquiry',
      cta_label: 'Make an appointment',
      join_label: 'Join Nesti',
      eyebrow: 'Property law · Closing counsel',
      lawyer_classic_design_version: 2,
    }, {
      animationType: 'slide-left',
      animationTrigger: 'load',
      animationDuration: 'slow',
      animationIntensity: 'medium',
      bg: '',
      width: 'full',
    }),
    block(T.ABOUT, {
      eyebrow: 'About the practice',
      heading: `About ${ctx.name}`,
      body: ctx.about || 'Practical legal counsel focused on protecting your transaction, documents, title, and closing timeline.',
    }, {
      animationType: 'slide-left',
      animationDuration: 'slow',
      animationIntensity: 'medium',
      bg: '',
      width: 'full',
      padding: 'none',
    }),
    block(T.WHO_WE_HELP, {
      eyebrow: 'Who we help',
      heading: 'Counsel for every side of the transaction',
      body: 'Buyers, sellers, refinancers, and property owners can start with a structured inquiry.',
      items: [
        { title: 'Home buyers', description: 'Review the agreement, conditions, title, and closing timeline before you commit.' },
        { title: 'Home sellers', description: 'Clarify obligations, closing funds, discharge, and registration requirements.' },
        { title: 'Refinancing', description: 'Coordinate lender requirements, payout statements, and registration with a clear file.' },
        { title: 'Investors and transfers', description: 'Organize ownership, title, and closing questions around the property at hand.' },
      ],
    }, {
      animationType: 'slide-up',
      animationDuration: 'medium',
      animationIntensity: 'medium',
      bg: '',
      width: 'full',
      padding: 'none',
      columns: 4,
    }),
    block(T.EXPERTISE, {
      eyebrow: 'Practice snapshot',
      heading: 'Where counsel is focused',
      body: 'A concise view of specializations, markets, and languages available for consultation.',
      process_label: 'How representation starts',
      process_heading: 'A clear path before any file is opened',
      process_body: 'This is an inquiry process, not legal advice or a promise of representation.',
    }, {
      animationType: 'slide-up',
      animationDuration: 'medium',
      animationIntensity: 'medium',
      bg: '',
      width: 'full',
      padding: 'none',
    }),
    block(T.PRACTICE_AREAS, {
      eyebrow: 'Legal services',
      heading: 'Our practice areas',
      body: 'Focused legal support for real estate decisions, documents, ownership, financing, and closing.',
      items: [
        { title: 'Residential Closings', description: 'Purchase and sale guidance from agreement through registration.' },
        { title: 'Commercial Real Estate', description: 'Practical support for commercial property transactions and documents.' },
        { title: 'Contract Review', description: 'Understand key obligations, conditions, timelines, and legal risks.' },
        { title: 'Title & Ownership', description: 'Resolve title, transfer, registration, and ownership concerns.' },
        { title: 'Refinancing', description: 'Coordinate lender requirements, payout statements, and registration.' },
        { title: 'Property Disputes', description: 'Organize the facts and identify an appropriate legal next step.' },
      ],
    }, {
      animationType: 'slide-up',
      animationDuration: 'medium',
      animationIntensity: 'medium',
      bg: '',
      width: 'full',
      padding: 'none',
      columns: 3,
    }),
    block(T.DOCUMENT_CHECKLIST, {
      eyebrow: 'File preparation',
      heading: 'What to send before we speak',
      body: 'A complete file helps the lawyer understand the matter without asking you to repeat the basics.',
      helper_text: 'Send copies, not originals, until representation is confirmed.',
      items: [
        { title: 'Agreement of purchase and sale', description: 'The signed offer, amendments, and any waivers or notices already exchanged.' },
        { title: 'Identification and parties', description: 'Legal names, contact details, and how title should be taken if that is already decided.' },
        { title: 'Financing documents', description: 'Mortgage commitment, payout statement, or private lending details if they exist.' },
        { title: 'Property and title papers', description: 'Listing details, survey, status certificate, or prior title documents you already have.' },
      ],
    }, {
      animationType: 'slide-up',
      animationDuration: 'medium',
      animationIntensity: 'medium',
      bg: '',
      width: 'full',
      padding: 'none',
      columns: 2,
    }),
    block(T.FEE_GUIDANCE, {
      eyebrow: 'Fee transparency',
      heading: 'How legal fees are typically framed',
      body: 'Use this as orientation before a consultation. It is not a quote, retainer, or promise of representation.',
      items: [
        { title: 'Legal fee range', description: 'Professional time for review, correspondence, signing, and registration is quoted for the specific matter.' },
        { title: 'Disbursements', description: 'Title search, registration, courier, and government charges are typically billed in addition to legal fees.' },
        { title: 'Land transfer and tax', description: 'Purchase files may include land transfer tax and related provincial charges. Final amounts depend on the transaction.' },
      ],
    }, {
      animationType: 'fade',
      animationDuration: 'slow',
      animationIntensity: 'subtle',
      bg: '#24211e',
      color: '#ffffff',
      width: 'full',
      padding: 'none',
      columns: 3,
    }),
    block(T.ROLE_DETAILS, {
      eyebrow: 'Legal transaction support',
      heading: 'Clear advice before you sign or close.',
      body: 'Understand the documents, deadlines, and legal risks before the transaction moves forward.',
      cta_label: 'Discuss your matter',
      highlights: [
        { title: 'Contract questions', text: 'Capture document review, agreement, condition, amendment, or clause concerns with context.' },
        { title: 'Closing preparation', text: 'Help visitors explain where they are in the transaction and what timeline they are working toward.' },
        { title: 'Title and transfer support', text: 'Route title, refinance, transfer, and closing service needs into a clearer legal intake.' },
      ],
    }, {
      animationType: 'fade',
      animationDuration: 'slow',
      animationIntensity: 'subtle',
      bg: '#24211e',
      color: '#ffffff',
      width: 'full',
      padding: 'none',
    }),
    block(T.CONSULTATION_OPTIONS, {
      eyebrow: 'Start the conversation',
      heading: 'Choose how you would like to begin',
      body: 'Pick the path that matches your timeline. Confidential details should wait until the lawyer confirms representation.',
      items: [
        { title: 'Send an inquiry', description: 'Share the property, documents, and closing date so the first response is useful.', cta_label: 'Submit inquiry', action: 'inquiry' },
        { title: 'Book a consultation', description: 'Request time to walk through the agreement, title issues, or closing requirements.', cta_label: 'Make an appointment', action: 'appointment' },
        { title: 'Request document review', description: 'Ask for a focused review of a contract, amendment, or closing package.', cta_label: 'Request review', action: 'inquiry' },
      ],
    }, {
      animationType: 'slide-up',
      animationDuration: 'medium',
      animationIntensity: 'medium',
      bg: '',
      width: 'full',
      padding: 'none',
      columns: 3,
    }),
    block(T.TESTIMONIALS, {
      eyebrow: 'Client feedback',
      heading: 'Happy clients',
      body: 'Buyers, sellers, and property owners who moved forward with confidence.',
    }, {
      animationType: 'slide-up',
      animationDuration: 'medium',
      animationIntensity: 'subtle',
      bg: '',
      width: 'full',
    }),
    block(T.CREDENTIALS, {
      eyebrow: 'Professional standing',
      heading: 'Your lawyer',
      body: 'Current practice activity and experience at a glance.',
      verification_label: 'Verified legal profile',
    }, {
      animationType: 'slide-up',
      animationDuration: 'medium',
      animationIntensity: 'medium',
      bg: '',
      width: 'full',
      padding: 'none',
      columns: 4,
    }),
    block(T.GUIDANCE, {
      eyebrow: 'Legal insights',
      heading: 'Your closing guide',
      body: 'A practical path from accepted offer to final registration and keys.',
      steps: [
        { title: 'Review the transaction', text: 'Share the property, agreement, financing, and closing timeline.' },
        { title: 'Resolve legal requirements', text: 'Identify document, title, registration, and signing requirements early.' },
        { title: 'Prepare for closing', text: 'Complete the final review, funds, signatures, and registration with clarity.' },
      ],
    }, {
      animationType: 'slide-up',
      animationDuration: 'medium',
      animationIntensity: 'subtle',
      bg: '',
      width: 'full',
      padding: 'none',
      columns: 3,
    }),
    block(T.FAQ, {
      eyebrow: 'Helpful questions',
      heading: 'What clients often ask',
      body: 'Clear answers to common questions before you start.',
      faqs: [
        { q: 'Is this legal advice?', a: 'No. This page starts an inquiry so the lawyer can review the matter and follow up appropriately.' },
        { q: 'Can I request a contract review?', a: 'Yes. Share the agreement, conditions, and timeline so the review request arrives with useful context.' },
        { q: 'What should I send before we speak?', a: 'The property address, agreement of purchase and sale, closing date, and any title or financing documents you already have.' },
        { q: 'When should I contact a lawyer?', a: 'As soon as an offer is being drafted or a closing date is in view — earlier contact leaves more time to resolve conditions and title issues.' },
        { q: 'What happens after I submit an inquiry?', a: 'The lawyer reviews the information, checks whether the matter is a fit, and contacts you about availability and next steps.' },
        { q: 'Can legal fees be confirmed before work begins?', a: 'Yes. Once the scope is clear, the lawyer can explain the expected legal fees, disbursements, and retainer requirements.' },
      ],
    }, {
      animationType: 'slide-up',
      animationDuration: 'medium',
      animationIntensity: 'subtle',
      bg: '',
      width: 'full',
      padding: 'none',
      columns: 1,
    }),
    block(T.CTA, {
      eyebrow: 'Consultation request',
      heading: 'If you need legal guidance, we are available.',
      body: 'Book a consultation or send the transaction details for a focused response.',
      cta_label: 'Get consultation',
      secondary_cta_label: 'Send inquiry',
    }, {
      animationType: 'fade',
      animationDuration: 'medium',
      animationIntensity: 'subtle',
      bg: '#d39a52',
      color: '#202020',
      width: 'full',
      padding: 'none',
    }),
    block(T.FOOTER, {
      heading: ctx.name,
      body: 'Real estate legal guidance for contracts, title matters, transactions, and closing.',
      role_label: 'Real Estate Lawyer',
      links_heading: 'Explore',
      contact_heading: 'Contact details',
      confidentiality_text: 'Do not send confidential information until the lawyer confirms representation.',
      items: [
        { label: 'About', target: '#about' },
        { label: 'Who we help', target: '#clients' },
        { label: 'Practice areas', target: '#services' },
        { label: 'Documents', target: '#documents' },
        { label: 'Closing guide', target: '#guidance' },
        { label: 'Contact', target: '/contact' },
      ],
    }, {
      animationType: 'fade',
      animationDuration: 'medium',
      animationIntensity: 'subtle',
      bg: '#202020',
      color: '#ffffff',
      width: 'full',
      padding: 'none',
    }),
  ],
};

export default lawyerClassic;
