import { block, brand, T } from '../shared/blockFactory';

const lawyerInvestor = {
  id: 'lawyer-investor',
  role: 'lawyer',
  experience: 'industrial-minimal',
  label: 'Investor Transaction Lawyer',
  tagline: 'Disciplined legal execution for active property investors',
  description: 'A ten-layer investor legal storefront for acquisitions, refinancing, assignments, title strategy, and repeat transaction intake.',
  features: ['Investor intake', 'Transaction safeguards', 'Practice KPIs', 'Portfolio-ready guidance'],
  brand: brand('#20252b', '#00a7c4', 'Inter', 'square', 'minimal', '#f3f6f7'),
  blocks: (ctx) => [
    block(T.HERO, {
        investor_design_version: 11,
      eyebrow: 'Investor transaction counsel',
      heading: ctx.headline || 'Transaction counsel for active investors',
      body: ctx.tagline || 'Structured legal support for acquisitions, refinances, assignments, entity transfers, and portfolio title work.',
      primary_cta_label: 'Start investor intake',
      cta_label: 'Book a strategy call',
      join_label: '',
    }, {
      bg: '#20252b',
      color: '#ffffff',
      padding: 'large',
      mediaPosition: 'portrait',
      animationType: 'fade',
      animationDuration: 'slow',
      animationIntensity: 'subtle',
    }),
    block(T.ABOUT, {
      eyebrow: 'Investor-focused legal practice',
      heading: 'Legal clarity for repeat transactions',
      body: ctx.about || 'A disciplined legal process helps investors move from agreement review to registration with fewer surprises, clearer responsibilities, and better-prepared files.',
      image_name: ctx.name,
      image_role: 'Investor transaction lawyer',
    }, {
      bg: '',
      color: '#20252b',
      padding: 'large',
      animationType: 'slide-up',
      animationIntensity: 'subtle',
    }),
    block(T.PRACTICE_SNAPSHOT, {
      eyebrow: 'Investor practice snapshot',
      heading: 'A practice built for active portfolios',
      body: 'A concise view of transaction focus, service markets, and consultation languages.',
      practice_focus_label: 'Investor practice focus',
      practice_focus_subtitle: 'Where counsel is concentrated',
      markets_label: 'Markets served',
      markets_subtitle: 'Locations and transaction contexts',
      languages_label: 'Languages spoken',
      languages_subtitle: 'Consultation accessibility',
    }, {
      columns: 3,
      padding: 'large',
      bg: '',
      color: '#20252b',
      animationType: 'slide-up',
      animationIntensity: 'subtle',
    }),
    block(T.SERVICES, {
      eyebrow: 'Investor legal services',
      heading: 'Support across the transaction lifecycle',
      body: 'Choose the workstream that matches the deal, ownership structure, financing, and closing timeline.',
      resource_label: 'Transaction workstreams',
      items: [
        { id: 'investor-service-acquisition', title: 'Acquisition review', description: 'Review agreements, conditions, title considerations, and closing requirements before the transaction advances.', icon: 'contract', link_disabled: true },
        { id: 'investor-service-refinance', title: 'Refinancing and lender work', description: 'Coordinate lender instructions, payouts, registrations, signing, and funding requirements.', icon: 'dollar', link_disabled: true },
        { id: 'investor-service-entity', title: 'Entity and ownership changes', description: 'Organize corporation, partnership, beneficial ownership, and transfer details for legal review.', icon: 'building', link_disabled: true },
        { id: 'investor-service-portfolio', title: 'Portfolio title support', description: 'Address title, registration, discharge, and ownership issues across repeat or multi-property files.', icon: 'landmark', link_disabled: true },
      ],
    }, {
      columns: 2,
      padding: 'large',
      bg: '',
      color: '#20252b',
      animationType: 'slide-up',
      animationIntensity: 'subtle',
    }),
    block(T.ROLE_DETAILS, {
      eyebrow: 'Transaction safeguards',
      heading: 'Protect the structure, timing, and exit',
      body: 'Investor files often involve layered financing, entities, tenancies, assignments, or compressed timelines. Surface the legal requirements early.',
      cta_label: 'Discuss the transaction',
      highlights: [
        { id: 'investor-safeguard-structure', title: 'Ownership structure', text: 'Confirm the purchasing entity, signing authority, beneficial ownership, and registration plan.', icon: 'building' },
        { id: 'investor-safeguard-timing', title: 'Conditions and timing', text: 'Track review periods, financing requirements, document delivery, funds, and closing deadlines.', icon: 'contract' },
        { id: 'investor-safeguard-title', title: 'Title and exit readiness', text: 'Identify registrations, discharges, restrictions, and title issues that can affect financing or resale.', icon: 'shield' },
      ],
    }, {
      columns: 3,
      padding: 'large',
      bg: '',
      color: '#20252b',
      animationType: 'fade',
      animationDuration: 'slow',
    }),
    block(T.PRACTICE_AREAS, {
      eyebrow: 'Investor workstreams',
      heading: 'Focused real estate legal support',
      body: 'A practical scope for active investors, ownership groups, and repeat transaction files.',
      items: [
        { id: 'investor-practice-purchases', title: 'Investment purchases', description: 'Agreement, title, financing, closing, and registration support for acquisitions.', icon: 'building' },
        { id: 'investor-practice-sales', title: 'Investment sales', description: 'Prepare the legal file for discharge, closing adjustments, deliverables, and completion.', icon: 'contract' },
        { id: 'investor-practice-refinancing', title: 'Portfolio refinancing', description: 'Coordinate lender instructions, payouts, registrations, and funding conditions.', icon: 'dollar' },
        { id: 'investor-practice-assignments', title: 'Assignments and transfers', description: 'Review transaction structure, consents, documents, and closing obligations.', icon: 'file' },
        { id: 'investor-practice-entities', title: 'Entity ownership', description: 'Organize corporate ownership, authority, registrations, and related documentation.', icon: 'landmark' },
        { id: 'investor-practice-title', title: 'Title strategy', description: 'Resolve title, discharge, registration, and ownership concerns before they delay a deal.', icon: 'shield' },
      ],
    }, {
      columns: 3,
      padding: 'large',
      bg: '',
      color: '#20252b',
      animationType: 'slide-up',
      animationIntensity: 'subtle',
    }),
    block(T.GUIDANCE, {
      eyebrow: 'Organized investor intake',
      heading: 'Move each file through a clear legal process',
      body: 'Prepare the transaction facts early so legal review can focus on risks, requirements, and the next decision.',
      steps: [
        { id: 'investor-step-deal', title: 'Share the deal', text: 'Provide the agreement, property, entity, financing, and target closing details.', icon: 'notebook' },
        { id: 'investor-step-structure', title: 'Confirm the structure', text: 'Clarify ownership, signing authority, lender requirements, and transaction-specific conditions.', icon: 'building' },
        { id: 'investor-step-review', title: 'Resolve legal requirements', text: 'Address title, documents, registrations, discharges, funds, and closing deliverables.', icon: 'shield' },
        { id: 'investor-step-close', title: 'Complete and report', text: 'Coordinate signing, registration, funding, completion, and final reporting for the file.', icon: 'gavel' },
      ],
    }, {
      columns: 4,
      padding: 'large',
      bg: '',
      color: '#20252b',
      animationType: 'slide-up',
      animationIntensity: 'subtle',
    }),
    block(T.CREDENTIALS, {
      eyebrow: 'Professional standing',
      heading: 'Investor practice at a glance',
      body: 'Current practice activity and experience for repeat transaction clients.',
      verification_label: 'Verified legal profile',
    }, {
      columns: 4,
      padding: 'medium',
      bg: '',
      color: '#20252b',
      animationType: 'fade',
      animationDuration: 'slow',
    }),
    block(T.CTA, {
      eyebrow: 'Next transaction',
      heading: 'Bring the next deal into focus',
      body: 'Share the property, agreement, entity, financing, and target closing date for a structured response.',
      cta_label: 'Start investor intake',
      secondary_cta_label: 'Book a strategy call',
    }, {
      padding: 'large',
      bg: '#007f95',
      color: '#ffffff',
      animationType: 'fade',
      animationIntensity: 'subtle',
    }),
    block(T.FOOTER, {
      eyebrow: 'Investor transaction lawyer',
      heading: ctx.company || ctx.name,
      body: 'Disciplined legal support for acquisitions, refinancing, ownership changes, title work, and repeat closings.',
      resource_heading: 'Investor legal desk',
      contact_heading: 'Start a transaction',
      disclaimer: 'Do not send confidential information until the lawyer confirms representation.',
      items: [
        { id: 'investor-footer-about', label: 'About', target: '#about' },
        { id: 'investor-footer-snapshot', label: 'Snapshot', target: '#practice-snapshot' },
        { id: 'investor-footer-services', label: 'Services', target: '#services' },
        { id: 'investor-footer-safeguards', label: 'Safeguards', target: '#buyer-protection' },
        { id: 'investor-footer-practice', label: 'Practice areas', target: '#practice-areas' },
        { id: 'investor-footer-guidance', label: 'Process', target: '#guidance' },
        { id: 'investor-footer-intake', label: 'Start intake', target: '#contact' },
      ],
    }, {
      padding: 'large',
      bg: '#12171c',
      color: '#ffffff',
    }),
  ],
};

export default lawyerInvestor;
